### ISSUE TITLE
Basepath variable

### ISSUE THREAD

**Issue by daemoned** [drone/jkl#2]
If I have a page in services/index.html and use my default layout which links to my css /css/bootstrap.css it cannot find it, only pages in the / root works. As I understand in Jekyll you solve it with a basepath variable infront of css/ and img/ in layouts but could not find anything like that in the code.

Is it a config error or a missing future?

**Comment by bradrydzewski** [comment]
it is a missing feature ... however, I just pushed a change that allows a `--base-url` flag to be included at the command line like this: `jkl --baseurl=/mybase`

You can then use the base url in your templates like this:

```
<a href="{{ .site.baseurl }}{{ .post.url }}">{{ .post.title }}</a>
```

One limitation is that the baseurl is only available in the templates, not in the markdown. This is because the markdown is not (currently) treated as a template and therefore has no access to these variables.

Let me know if this change works for you

**Comment by daemoned** [comment]
Works likes I wan't it to, thx for the quick fix and respone.
Keep up the good work.
